name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  ### runner machine

    strategy:
      matrix:
        python-version: [3.8, 3.9]  ### we have declared,two env, so job will be executed

    steps:  ### This is, we are declaring the stages ####
    ### below code is from the github doc refer for other projects #####
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
